[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true }
bevy_image = { version = "0.16", features = ["jpeg", "png"] }
spacetimedb-sdk = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
